name: stash_test
version: 5.0.1
description: >-
  Provides the testing support needed in order to implement extensions to the base stash
  package
homepage: https://github.com/ivoleitao/stash
repository: https://github.com/ivoleitao/stash
issue_tracker: https://github.com/ivoleitao/stash/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Flutter shared dependencies
  clock: ^1.1.1
  test: ^1.24.3
  # Other dependencies
  equatable: ^2.0.5
  time: ^2.1.3
  stash: ^5.0.1
dev_dependencies:
  lints: ^2.1.1