name: stash_isar
version: 5.2.0
description: >-
  Isar storage extension for the stash caching API. Provides support to store vaults 
  and caches in the Isar database
homepage: https://github.com/ivoleitao/stash
repository: https://github.com/ivoleitao/stash
issue_tracker: https://github.com/ivoleitao/stash/issues

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  # Flutter shared dependencies
  meta: ^1.11.0
  # Other dependencies
  isar: ^3.1.0+1
  stash: ^5.2.0
dev_dependencies:
  # Flutter shared dependencies
  test: ^1.24.9
  # Other dependencies
  lints: ^3.0.0
  build_runner: ^2.4.9
  isar_generator: ^3.1.0+1
  stash_test: ^5.1.1