name: stash_file
version: 5.1.1
description: >-
  File storage extension for the stash API. Provides support to store vaults 
  and caches in the local file system in binary format using the msgpack json format
homepage: https://github.com/ivoleitao/stash
repository: https://github.com/ivoleitao/stash
issue_tracker: https://github.com/ivoleitao/stash/issues

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  # Flutter shared dependencies
  meta: ^1.10.0
  path: ^1.8.3
  # Other dependencies
  file: ^7.0.0
  stream_transform: ^2.1.0
  stash: ^5.1.0
dev_dependencies:
  # Flutter shared dependencies
  test: ^1.24.9
  # Other dependencies
  lints: ^3.0.0
  stash_test: ^5.1.0
  build_runner: ^2.4.8