name: stash_secure_storage_example
description: Demonstrates how to use the stash_secure_storage plugin
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  stash: ^5.0.3
  stash_secure_storage:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
