name: stash_memory
version: 5.0.2
description: >-
  Memory storage extension for the stash API. Provides support to store vaults 
  and caches in-memory
homepage: https://github.com/ivoleitao/stash
repository: https://github.com/ivoleitao/stash
issue_tracker: https://github.com/ivoleitao/stash/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  stash: ^5.0.1
dev_dependencies:
  # Flutter shared dependencies
  test: ^1.24.3
  # Other dependencies
  lints: ^2.1.1
  stash_test: ^5.0.1