name: stash_memory
version: 5.1.0
description: >-
  Memory storage extension for the stash API. Provides support to store vaults 
  and caches in-memory
homepage: https://github.com/ivoleitao/stash
repository: https://github.com/ivoleitao/stash
issue_tracker: https://github.com/ivoleitao/stash/issues

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  stash: ^5.0.3
dev_dependencies:
  # Flutter shared dependencies
  test: ^1.24.9
  # Other dependencies
  lints: ^3.0.0
  stash_test: ^5.0.3