name: stash_shared_preferences_example
description: Demonstrates how to use the stash_shared_preferences plugin
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  stash: ^5.1.1
  stash_shared_preferences:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true