name: stash
version: 5.0.2
description: >-
  Stash is a key-value store abstraction with plain and cache driven semantics 
  and support for a pluggable backend architecture.
homepage: https://github.com/ivoleitao/stash
repository: https://github.com/ivoleitao/stash
issue_tracker: https://github.com/ivoleitao/stash/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Flutter shared dependencies
  meta: ^1.9.1
  clock: ^1.1.1
  async: ^2.11.0
  # Other dependencies
  equatable: ^2.0.5
  uuid: ^4.1.0
dev_dependencies:
  # Flutter shared dependencies
  test: ^1.24.3
  # Other dependencies
  lints: ^2.1.1